### ISSUE TITLE
Selector UDP/MQTT  not work

### ISSUE THREAD

**Issue by madito** [Gagi2k/LoxBerry-Plugin-WifiScanner#8] opened 2020-10-10 19:21 UTC
The button not work, always save UDP_ENABLED=1

**Comment by Gagi2k** [comment] 2020-10-10 19:37
Duplicate of https://github.com/Gagi2k/LoxBerry-Plugin-WifiScanner/issues/7

**Closed as completed by Gagi2k** 2020-10-10 19:37 UTC
